### ISSUE TITLE
I am trying to scale gif files using your pellet gen commands but transperency is lost 

### ISSUE THREAD

**Issue by PratapOdedara** [thevangelist/FFMPEG-gif-script-for-bash#2]
How can I achive transperency while resizing gif using ffmpeg commands I am trying with this images the original and resized images are atteched with this issue

**Comment by thevangelist** [comment]
My gut says no, but apparently there's some possibilities. I'll get back to you if I come up with a solution. Meanwhile, check for example: http://stackoverflow.com/questions/10438713/overlay-animated-images-with-transparency-over-a-static-background-image-using-f

**Comment by PratapOdedara** [comment]
Does anybody get solution of this problem?

**Comment by thevangelist** [comment]
Did not understand the question, so closing.
